/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux ubuntu64-vm 3.2.0-24-generic #37-Ubuntu SMP Wed Apr 25 08:43:22 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux"
#define BUILD_ENV_DATE "2015年 04月 13日 星期一 21:17:43 CST"
#define BUILD_ENV_SRCDIR "/home/linux/workdir/samba-3.0.23/source"
#define BUILD_ENV_BUILDDIR "/home/linux/workdir/samba-3.0.23/source"
#define BUILD_ENV_USER "linux"
#define BUILD_ENV_HOST "ubuntu64-vm"
#define BUILD_ENV_COMPILER "arm-none-linux-gnueabi-gcc"
#endif /* _BUILD_ENV_H */
